return {
	dashboard = {
		find_file		= "󰱼 ",
		settings		= " ",
		quit			= "󰿅 ",
		lazy_manager	= "󰒲 ",
		explorer		= "󰙅 ",
		mason			= " ",
	},
	misc = {
		blank_square	= "󰝤 ",
		tab				= "│ ",
		space			= "·",
		trail			= "~",
	},
	dap = {
		breakpoint	= " ",
	},
	diagnostics = {
		error			= " ",
		warn			= " ",
		info			= " ",
		hint			= " ",
		virtual_prefix	= " ",
	},
	cmp_menu = {
		nvim_lsp	= " ",
		buffer		= " ",
		path		= " ",
	},
	cmp_kind = {
		Array			= " ",
		Boolean			= "󰨙 ",
		Class			= " ",
		Color			= " ",
		Constant		= " ",
		Constructor		= "󱢇 ",
		Enum			= " ",
		EnumMember		= " ",
		Event			= " ",
		Field			= " ",
		File			= " ",
		Folder			= "󰉋 ",
		Function		= "󰊕 ",
		Interface		= " ",
		Key				= " ",
		Keyword			= " ",
		Method			= "󰊕 ",
		Module			= " ",
		Namespace		= "󰦮 ",
		Null			= "󰟢 ",
		Number			= " ",
		Object			= " ",
		Operator		= " ",
		Package			= " ",
		Property		= " ",
		Reference		= " ",
		Snippet			= " ",
		String			= " ",
		Struct			= " ",
		Text			= " ",
		TypeParameter	= " ",
		Unit			= " ",
		Value			= " ",
		Variable		= "󰀫 ",
	},
}
